---
title: "Pubmed Results"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny  
---

<!-- Each level 1 header (#) begins a new page in the dashboard. -->
<!-- Each level 2 header (##) begins a new column. -->
<!-- Each level 3 header (###) begins a new row. -->


Layout, show available datasets, show crossing. 

```{r setup, include=FALSE}
library(flexdashboard)
library(here)
library(rvest)
library(dplyr)
library(readr)
library(tidyr) #crossing() function
library(stringr)
library(purrr)

library(parallel)
library(shiny)
library(DT)
```



```{r load data, include= FALSE}

warhead_db <- read_csv(here("data", "raw_data", "warhead.csv"))
ordo <- read_csv(here("data", "processed_data", "ordo_post_03.csv"))
protac_db <- read_csv(here("data", "raw_data", "protac.csv"))
linkers <- read_csv(here("data", "raw_data", "linker.csv"))
```


# ORDO

```{r}
ordo |>  select(c(id, name, parents, children, ancestors, icd10, 
             mesh, meddra, umls, omim,
             icd11, ensembl, genatlas, 
             hgnc, swissprot, reactome, iuphar)) |> DT::datatable()
```   
 
# WARHEAD
    
```{r}
warhead_db  |> DT::datatable()
```

# PROTAC 
    
```{r}
protac_db   |>DT::datatable()
```

# LINKERS
    
```{r}
linkers |>  DT::datatable()
```






